version: '3.1'

services:

  backend:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    env_file:
      - backend.env

  mongo:
    image: mongo
    restart: always
    environment:
      - mongo.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - mongo.env